# Generated by Django 5.2.17 on 2026-09-13 08:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('junior-high-school', 'Middle School'), ('high-school', 'High School'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's"), ('master', "Master's"), ('doctorate', 'Doctorate'), ('certification', 'Certification')], default='bachelor', max_length=20)),
                ('field_of_study', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('internship', 'Internship'), ('research', 'Research'), ('volunteer', 'Volunteer'), ('part-time', 'Part-Time'), ('full-time', 'Full-Time'), ('freelance', 'Freelance'), ('organizaiton', 'Organization')], default='full-time', max_length=20),
        ),
    ]
