# Generated by Django 5.2.17 on 2026-09-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education_alter_experience_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
