# Generated by Django 5.2.17 on 2026-09-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='logo_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
